- name: Crea y Configura Cluster OKE y VMs
  hosts: localhost
  gather_facts: false
  connection: local

  vars_files: vault.yaml

  vars:
    node_pool_config_details:
      size: 3
      placement_configs:
        - availability_domain: "{{ ad1 }}"
          subnet_id: "{{ ad1_subnet_id }}"
        - availability_domain: "{{ ad2 }}"
          subnet_id: "{{ ad2_subnet_id }}"
        - availability_domain: "{{ ad3 }}"
          subnet_id: "{{ ad3_subnet_id }}"

  tasks:
  - name: Lista Subnets AD1
    oracle.oci.oci_network_subnet_facts:
      compartment_id: "{{ compartment_ocid }}"
      display_name: "{{ subnet1_name }}"
    register: resultado
  
  - set_fact:
     ad1_subnet_id: "{{ resultado.subnets[0].id }}"
  
  - name: Lista Subnets AD2
    oracle.oci.oci_network_subnet_facts:
      compartment_id: "{{ compartment_ocid }}"
      display_name: "{{ subnet2_name }}"
    register: resultado
  
  - set_fact:
     ad2_subnet_id: "{{ resultado.subnets[0].id }}"
  
  - name: Lista Subnets AD3
    oracle.oci.oci_network_subnet_facts:
      compartment_id: "{{ compartment_ocid }}"
      display_name: "{{ subnet3_name }}"
    register: resultado

  - set_fact:
     ad3_subnet_id: "{{ resultado.subnets[0].id }}"

  - name: Lista LB Subnet
    oracle.oci.oci_network_subnet_facts:
      compartment_id: "{{ compartment_ocid }}"
      display_name: "{{ lb_subnet1_name }}"
    register: resultado

  - set_fact:
      lb_subnet1_id: "{{ resultado.subnets[0].id }}"

  - name: Lista LB Subnet
    oracle.oci.oci_network_subnet_facts:
      compartment_id: "{{ compartment_ocid }}"
      display_name: "{{ subnet1_name }}"
    register: resultado

  - set_fact:
      lb_subnet2_id: "{{ resultado.subnets[0].id }}"

  - name: Valida Ultima Version Disponible de k8s
    oracle.oci.oci_container_engine_cluster_options_facts:
      cluster_option_id: all
    register: k8s_resultado

  - set_fact:
      k8s_version: "{{ k8s_resultado.cluster_options.kubernetes_versions[3] }}"

  - name: Lista Todas las VCNs
    oracle.oci.oci_network_vcn_facts:
       compartment_id: "{{ compartment_ocid }}"
       display_name: "{{ vcn_name }}"
    register: vcn_resultado
  
  - set_fact:
      vcn_id: "{{ vcn_resultado.vcns[0].id }}"  

  - name: Crea Cluster OKE
    oracle.oci.oci_container_engine_cluster:
      compartment_id: "{{ compartment_ocid }}"
      name: "{{ cluster_name }}"
      vcn_id: "{{ vcn_id }}"
      kubernetes_version: "{{ k8s_version }}"
      options:
        service_lb_subnet_ids:
          - "{{ lb_subnet1_id }}"
          - "{{ lb_subnet2_id }}"
    register: k8s_cluster_result

  - set_fact:
      cluster_id: "{{ k8s_cluster_result.cluster.id }}"
  
  - name: Valida Shape Disponibles para Crear Nodos en Cluster
    oracle.oci.oci_container_engine_node_pool_options_facts:
      id: "{{ cluster_id }}"
    register: shape_resultado

  - debug:
      msg: "{{ shape_resultado }}"

  - set_fact:
      node_image_name: "{{ shape_resultado.node_pool_options.images[0] }}"

  - set_fact:
      node_shape: "{{ item }}"
    loop: "{{ shape_resultado.node_pool_options.shapes }}"
    when: 
      - '"VM.Standard" in item'

  - set_fact:
      node_pool_source_details:
        source_type: "IMAGE"
        image_id: "{{ item.image_id }}"
    loop: "{{ shape_resultado.node_pool_options.sources }}"
    when: 
      - item.source_name.find("7.6") == -1
      - item.source_name.find("aarch64") == -1
  
#  - name: Crea Node Pool
#    oracle.oci.oci_container_engine_node_pool:
#      cluster_id: "{{ cluster_id }}"
#      compartment_id: "{{ compartment_ocid }}"
#      name: "{{ node_pool_name }}"
#      kubernetes_version: "{{ k8s_version }}"
#      node_source_details: "{{ node_pool_source_details }}"
#      node_shape: "{{ node_shape }}"
#      node_config_details: "{{ node_pool_config_details }}"
#    register: np_resultado

  - name: Create a node pool
    oracle.oci.oci_container_engine_node_pool:
      cluster_id: "{{ cluster_id }}"
      compartment_id: "{{ compartment_ocid }}"
      name: "{{ node_pool_name }}"
      kubernetes_version: "{{ k8s_version }}"
      node_image_name: "{{ node_image_name }}"
      node_shape: "{{ node_shape }}"
      quantity_per_subnet: 1
      subnet_ids:
        - "{{ ad1_subnet_id }}"
        - "{{ ad2_subnet_id }}"
        - "{{ ad3_subnet_id }}"
    register: resultado


  - set_fact:
      node_pool_id: "{{ resultado.node_pool.id }}"


#  - debug:
#      msg: "{{ np_resultado }}"

#  - set_fact:
#      node_pool_id: "{{ np_resultado.node_pool.id }}"
  
  
#  - name: Crea kubeconfig
#    oracle.oci.oci_container_engine_kubeconfig:
#      cluster_id: "{{ cluster_id }}"
#    register: result
  
#  - name: Almacena Kubeconfig
#    copy:
#      content: "{{ result.kubeconfig }}"
#      dest: "{{ kubeconfig_path }}"
